[package]
name = "postgis_topology_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
pgrx = "0.11.1"

[lib]
crate-type = ["cdylib"]

[features]
default = ["pg14"]

[package.metadata.pgrx]
name = "postgis_topology_rust"